spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:just-mem
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


management:
  endpoints:
    web:
      exposure:
        include: *